import { describeGraphType } from "./graph_spec_builder";
import type { DesiredOutput, ExperimentDesign, GraphSpec, StatRecommendation, TableProfile } from "./types";

type RCodeInput = {
  profile: TableProfile;
  design: ExperimentDesign;
  recommendation: StatRecommendation;
  selectedOutputs: DesiredOutput[];
  graphSpec: GraphSpec | null;
};

function unique<T>(items: Array<T | null | undefined | false>): T[] {
  return Array.from(new Set(items.filter(Boolean) as T[]));
}

function rString(value: string): string {
  return JSON.stringify(value);
}

function rVector(values: string[]): string {
  if (!values.length) return "character(0)";
  return `c(${values.map(rString).join(", ")})`;
}

function rName(column: string): string {
  return `\`${column.replace(/\\/g, "\\\\").replace(/`/g, "\\`")}\``;
}

function outputSelected(outputs: DesiredOutput[], value: DesiredOutput): boolean {
  return outputs.includes(value);
}

function firstNumericPredictor(profile: TableProfile, outcome?: string): string | undefined {
  return profile.numericOutcomeColumns.find((column) => column !== outcome);
}

function inferSecondFactor(profile: TableProfile, design: ExperimentDesign, graphSpec: GraphSpec | null): string | undefined {
  return unique([
    graphSpec?.facetBy[0],
    graphSpec?.splitBy[0],
    design.timeColumn,
    profile.possibleGroupColumns.find((column) => column !== design.groupColumn)
  ])[0];
}

function recommendedFormula(input: RCodeInput): string {
  const { design, profile, recommendation, graphSpec } = input;
  const outcome = design.measurementColumn ?? profile.numericOutcomeColumns[0] ?? "YOUR_MEASUREMENT_COLUMN";
  const group = design.groupColumn;
  const time = design.timeColumn;
  const subject = design.subjectIdColumn;
  const predictor = firstNumericPredictor(profile, outcome) ?? graphSpec?.xAxis ?? "YOUR_PREDICTOR_COLUMN";
  const secondFactor = inferSecondFactor(profile, design, graphSpec) ?? "YOUR_SECOND_FACTOR_COLUMN";

  if (recommendation.id === "linear-mixed-effects-model" && subject && time) {
    return group
      ? `${rName(outcome)} ~ ${rName(group)} * ${rName(time)} + (1 | ${rName(subject)})`
      : `${rName(outcome)} ~ ${rName(time)} + (1 | ${rName(subject)})`;
  }

  if (recommendation.id === "two-way-anova" && group) {
    return `${rName(outcome)} ~ ${rName(group)} * ${rName(secondFactor)}`;
  }

  if (recommendation.id === "linear-regression") {
    return `${rName(outcome)} ~ ${rName(predictor)}`;
  }

  if (group) {
    return `${rName(outcome)} ~ ${rName(group)}`;
  }

  return `${rName(outcome)} ~ 1`;
}

function requiredColumns(input: RCodeInput): string[] {
  const { design, graphSpec, profile, recommendation } = input;
  const outcome = design.measurementColumn ?? profile.numericOutcomeColumns[0];
  const predictor = recommendation.id === "linear-regression" ? firstNumericPredictor(profile, outcome) ?? graphSpec?.xAxis : undefined;
  const secondFactor = recommendation.id === "two-way-anova" ? inferSecondFactor(profile, design, graphSpec) : undefined;

  return unique([
    outcome,
    design.groupColumn,
    design.timeColumn,
    design.subjectIdColumn,
    predictor,
    secondFactor,
    graphSpec?.xAxis,
    graphSpec?.yAxis,
    graphSpec?.colorBy,
    ...(graphSpec?.facetBy ?? []),
    ...(graphSpec?.splitBy ?? [])
  ]);
}

function requiredPackages(input: RCodeInput): string[] {
  const { recommendation, selectedOutputs, graphSpec } = input;
  return unique([
    "readr",
    "readxl",
    "dplyr",
    "tibble",
    "broom",
    outputSelected(selectedOutputs, "graph") && graphSpec?.graphRequested && "ggplot2",
    outputSelected(selectedOutputs, "formatted_table") && "writexl",
    (recommendation.family === "anova" || recommendation.family === "mixed_model") && "emmeans",
    recommendation.family === "mixed_model" && "lme4",
    recommendation.family === "mixed_model" && "lmerTest",
    recommendation.family === "mixed_model" && "broom.mixed"
  ]);
}

function setupBlock(input: RCodeInput): string {
  const columns = requiredColumns(input);
  const packages = requiredPackages(input);
  return `# ---- 1. Setup ----
# This script was generated by Statistics Navigator for Non-Statisticians.
# Review column choices and assumptions before using this in a thesis, paper, or report.

required_packages <- ${rVector(packages)}
missing_packages <- required_packages[!vapply(required_packages, requireNamespace, logical(1), quietly = TRUE)]
if (length(missing_packages) > 0) {
  install.packages(missing_packages)
}
invisible(lapply(required_packages, library, character.only = TRUE))

# ---- 2. Choose your data table ----
# Option A, easiest in RStudio: leave data_path blank and select your CSV/XLS/XLSX file
# when the file picker opens.
# Option B: paste the full path between the quotes, for example:
# data_path <- "/Users/your-name/Desktop/my_table.xlsx"
data_path <- ""

if (identical(data_path, "") && interactive()) {
  message("Choose your CSV/XLS/XLSX data table.")
  data_path <- file.choose()
}

if (identical(data_path, "")) {
  stop("No data table selected. Paste a file path into data_path, or run this script interactively in RStudio and choose a file.")
}

if (!file.exists(data_path)) {
  stop("The selected data file was not found: ", data_path)
}

output_dir <- "statnav_r_outputs"
dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)

file_extension <- tolower(tools::file_ext(data_path))
if (file_extension %in% c("xlsx", "xls")) {
  raw_data <- readxl::read_excel(data_path)
} else if (file_extension == "csv") {
  raw_data <- readr::read_csv(data_path, show_col_types = FALSE)
} else {
  stop("Unsupported file type: .", file_extension, ". Please choose a CSV, XLS, or XLSX file.")
}

data <- as.data.frame(raw_data)
required_columns <- ${rVector(columns)}
missing_columns <- setdiff(required_columns, names(data))
if (length(missing_columns) > 0) {
  stop("Missing required columns: ", paste(missing_columns, collapse = ", "))
}

analysis_data <- data[, required_columns, drop = FALSE]
analysis_data <- analysis_data[stats::complete.cases(analysis_data), , drop = FALSE]
message("Rows used after removing missing required values: ", nrow(analysis_data))
`;
}

function coercionBlock(input: RCodeInput): string {
  const { design, graphSpec, recommendation, profile } = input;
  const outcome = design.measurementColumn ?? profile.numericOutcomeColumns[0] ?? "YOUR_MEASUREMENT_COLUMN";
  const group = design.groupColumn;
  const time = design.timeColumn;
  const subject = design.subjectIdColumn;
  const secondFactor = recommendation.id === "two-way-anova" ? inferSecondFactor(profile, design, graphSpec) : undefined;

  const lines = [
    "# ---- 3. Column preparation ----",
    `analysis_data[[${rString(outcome)}]] <- as.numeric(analysis_data[[${rString(outcome)}]])`,
    group && `analysis_data[[${rString(group)}]] <- as.factor(analysis_data[[${rString(group)}]])`,
    subject && `analysis_data[[${rString(subject)}]] <- as.factor(analysis_data[[${rString(subject)}]])`,
    secondFactor && `analysis_data[[${rString(secondFactor)}]] <- as.factor(analysis_data[[${rString(secondFactor)}]])`,
    time && `# Keep ${time} numeric when it represents ordered sessions; otherwise convert it to factor.`,
    time && `if (!is.numeric(analysis_data[[${rString(time)}]])) analysis_data[[${rString(time)}]] <- as.factor(analysis_data[[${rString(time)}]])`
  ];

  return `${lines.filter(Boolean).join("\n")}\n`;
}

function tableWriteBlock(input: RCodeInput, resultObjectName = "result_table"): string {
  if (!outputSelected(input.selectedOutputs, "formatted_table")) {
    return `readr::write_csv(${resultObjectName}, file.path(output_dir, "${resultObjectName}.csv"))`;
  }

  return `readr::write_csv(${resultObjectName}, file.path(output_dir, "${resultObjectName}.csv"))
writexl::write_xlsx(list(${resultObjectName} = ${resultObjectName}), file.path(output_dir, "${resultObjectName}.xlsx"))`;
}

function analysisBlock(input: RCodeInput): string {
  const { design, graphSpec, profile, recommendation } = input;
  const outcome = design.measurementColumn ?? profile.numericOutcomeColumns[0] ?? "YOUR_MEASUREMENT_COLUMN";
  const group = design.groupColumn ?? "YOUR_GROUP_COLUMN";
  const time = design.timeColumn ?? "YOUR_TIME_COLUMN";
  const subject = design.subjectIdColumn ?? "YOUR_SUBJECT_ID_COLUMN";
  const predictor = firstNumericPredictor(profile, outcome) ?? graphSpec?.xAxis ?? "YOUR_PREDICTOR_COLUMN";
  const formula = recommendedFormula(input);

  if (recommendation.id === "linear-mixed-effects-model") {
    return `# ---- 4. Recommended analysis: ${recommendation.recommendedAnalysis} ----
model_formula <- stats::as.formula(${rString(formula)})
model <- lmerTest::lmer(model_formula, data = analysis_data)

model_summary <- summary(model)
print(model_summary)

anova_table <- as.data.frame(stats::anova(model))
anova_table <- tibble::rownames_to_column(anova_table, "term")
fixed_effects <- broom.mixed::tidy(model, effects = "fixed", conf.int = TRUE)

readr::write_csv(anova_table, file.path(output_dir, "anova_fixed_effects.csv"))
readr::write_csv(fixed_effects, file.path(output_dir, "model_fixed_effects.csv"))

if (${rString(group)} %in% names(analysis_data) && ${rString(time)} %in% names(analysis_data)) {
  pairwise_by_time <- emmeans::emmeans(model, specs = stats::as.formula(paste("pairwise ~", ${rString(group)}, "|", ${rString(time)})))
  capture.output(pairwise_by_time, file = file.path(output_dir, "pairwise_group_comparisons.txt"))
}

if (${rString(group)} %in% names(analysis_data) && is.numeric(analysis_data[[${rString(time)}]])) {
  group_slopes <- emmeans::emtrends(model, specs = stats::as.formula(paste("pairwise ~", ${rString(group)})), var = ${rString(time)})
  capture.output(group_slopes, file = file.path(output_dir, "group_slope_comparisons.txt"))
}
`;
  }

  if (recommendation.id === "paired-t-test" || recommendation.id === "wilcoxon-matched-pairs") {
    const testFunction = recommendation.id === "wilcoxon-matched-pairs" ? "stats::wilcox.test" : "stats::t.test";
    return `# ---- 4. Recommended analysis: ${recommendation.recommendedAnalysis} ----
wide_data <- stats::reshape(
  analysis_data[, c(${rString(subject)}, ${rString(group)}, ${rString(outcome)})],
  idvar = ${rString(subject)},
  timevar = ${rString(group)},
  direction = "wide"
)
value_columns <- grep(paste0("^", ${rString(outcome)}, "\\\\."), names(wide_data), value = TRUE)
if (length(value_columns) != 2) {
  stop("Paired analysis needs exactly two condition columns after reshaping.")
}
test_result <- ${testFunction}(wide_data[[value_columns[1]]], wide_data[[value_columns[2]]], paired = TRUE)
result_table <- broom::tidy(test_result)
${tableWriteBlock(input)}
print(test_result)
`;
  }

  if (recommendation.id === "unpaired-t-test" || recommendation.id === "mann-whitney") {
    const testFunction = recommendation.id === "mann-whitney" ? "stats::wilcox.test" : "stats::t.test";
    const extraArg = recommendation.id === "unpaired-t-test" ? ", var.equal = FALSE" : "";
    return `# ---- 4. Recommended analysis: ${recommendation.recommendedAnalysis} ----
test_formula <- stats::as.formula(${rString(formula)})
test_result <- ${testFunction}(test_formula, data = analysis_data${extraArg})
result_table <- broom::tidy(test_result)
${tableWriteBlock(input)}
print(test_result)
`;
  }

  if (recommendation.id === "one-way-anova" || recommendation.id === "two-way-anova") {
    const emmeansSpec = recommendation.id === "two-way-anova"
      ? `stats::as.formula(paste("pairwise ~", ${rString(group)}, "|", ${rString(inferSecondFactor(profile, design, graphSpec) ?? "YOUR_SECOND_FACTOR_COLUMN")}))`
      : `stats::as.formula(paste("pairwise ~", ${rString(group)}))`;
    return `# ---- 4. Recommended analysis: ${recommendation.recommendedAnalysis} ----
model_formula <- stats::as.formula(${rString(formula)})
model <- stats::aov(model_formula, data = analysis_data)
anova_table <- broom::tidy(model)
${tableWriteBlock(input, "anova_table")}

posthoc <- emmeans::emmeans(model, specs = ${emmeansSpec})
capture.output(posthoc, file = file.path(output_dir, "posthoc_emmeans.txt"))
print(summary(model))
`;
  }

  if (recommendation.id === "linear-regression") {
    return `# ---- 4. Recommended analysis: ${recommendation.recommendedAnalysis} ----
analysis_data[[${rString(predictor)}]] <- as.numeric(analysis_data[[${rString(predictor)}]])
model_formula <- stats::as.formula(${rString(formula)})
model <- stats::lm(model_formula, data = analysis_data)
result_table <- broom::tidy(model, conf.int = TRUE)
model_fit <- broom::glance(model)
${tableWriteBlock(input)}
readr::write_csv(model_fit, file.path(output_dir, "model_fit.csv"))
print(summary(model))
`;
  }

  if (recommendation.id === "kruskal-wallis") {
    return `# ---- 4. Recommended analysis: ${recommendation.recommendedAnalysis} ----
test_formula <- stats::as.formula(${rString(formula)})
test_result <- stats::kruskal.test(test_formula, data = analysis_data)
result_table <- broom::tidy(test_result)
${tableWriteBlock(input)}
print(test_result)
`;
  }

  if (recommendation.id === "fisher-or-chi-square" || recommendation.id === "chi-square") {
    return `# ---- 4. Recommended analysis: ${recommendation.recommendedAnalysis} ----
contingency_table <- table(analysis_data[[${rString(group)}]], analysis_data[[${rString(outcome)}]])
expected_counts <- suppressWarnings(stats::chisq.test(contingency_table)$expected)
test_result <- if (all(dim(contingency_table) == c(2, 2)) || any(expected_counts < 5)) {
  stats::fisher.test(contingency_table)
} else {
  stats::chisq.test(contingency_table)
}
result_table <- broom::tidy(test_result)
${tableWriteBlock(input)}
readr::write_csv(as.data.frame(contingency_table), file.path(output_dir, "contingency_table.csv"))
print(test_result)
`;
  }

  return `# ---- 4. Recommended analysis: review needed ----
# The current recommendation is: ${recommendation.recommendedAnalysis}
# This design needs manual review before running a final inferential model.
message("Review the recommendation and fill in the appropriate R model/test manually.")
`;
}

function graphBlock(input: RCodeInput): string {
  const { graphSpec, selectedOutputs, design, profile } = input;
  if (!outputSelected(selectedOutputs, "graph") || !graphSpec?.graphRequested) return "";

  const graphType = graphSpec.graphType;
  const xAxis = graphSpec.xAxis ?? design.groupColumn ?? design.timeColumn ?? "YOUR_X_AXIS_COLUMN";
  const yAxis = graphSpec.yAxis ?? design.measurementColumn ?? profile.numericOutcomeColumns[0] ?? "YOUR_Y_AXIS_COLUMN";
  const colorBy = graphSpec.colorBy ?? design.groupColumn;
  const facetBy = unique([...graphSpec.facetBy, ...graphSpec.splitBy]);
  const errorBar = graphSpec.showErrorBars ? graphSpec.errorBarType : "none";

  const facetLine = facetBy.length
    ? `p <- p + ggplot2::facet_wrap(stats::as.formula(paste("~", paste(${rVector(facetBy)}, collapse = " + "))))`
    : "# No separate panels requested.";

  if (graphType === "line_mean_sem" || graphType === "longitudinal_line") {
    const groupVars = unique([xAxis, colorBy, ...facetBy]);
    return `
# ---- 5. Requested graph: ${describeGraphType(graphType)} ----
x_axis <- ${rString(xAxis)}
y_axis <- ${rString(yAxis)}
color_by <- ${colorBy ? rString(colorBy) : "NULL"}
facet_by <- ${rVector(facetBy)}
summary_vars <- ${rVector(groupVars)}

plot_summary <- analysis_data |>
  dplyr::group_by(dplyr::across(dplyr::all_of(summary_vars))) |>
  dplyr::summarise(
    n = sum(!is.na(.data[[y_axis]])),
    mean = mean(.data[[y_axis]], na.rm = TRUE),
    sd = stats::sd(.data[[y_axis]], na.rm = TRUE),
    sem = sd / sqrt(n),
    .groups = "drop"
  )

p <- ggplot2::ggplot(plot_summary, ggplot2::aes(x = .data[[x_axis]], y = mean))
if (!is.null(color_by)) {
  p <- p + ggplot2::aes(color = .data[[color_by]], group = .data[[color_by]])
}
p <- p + ggplot2::geom_line(linewidth = 0.9) + ggplot2::geom_point(size = 2.4)
${errorBar === "SEM" ? "p <- p + ggplot2::geom_errorbar(ggplot2::aes(ymin = mean - sem, ymax = mean + sem), width = 0.12)" : ""}
${facetLine}
p <- p + ggplot2::theme_classic(base_size = 13) + ggplot2::labs(
  title = ${rString(describeGraphType(graphType))},
  x = x_axis,
  y = paste("Mean", y_axis),
  color = color_by
)
ggplot2::ggsave(file.path(output_dir, "requested_graph.png"), p, width = 8, height = 5, dpi = 300)
print(p)
`;
  }

  if (graphType === "scatter_regression" || graphType === "trendline") {
    return `
# ---- 5. Requested graph: ${describeGraphType(graphType)} ----
x_axis <- ${rString(xAxis)}
y_axis <- ${rString(yAxis)}
color_by <- ${colorBy ? rString(colorBy) : "NULL"}
p <- ggplot2::ggplot(analysis_data, ggplot2::aes(x = .data[[x_axis]], y = .data[[y_axis]]))
if (!is.null(color_by)) p <- p + ggplot2::aes(color = .data[[color_by]])
p <- p + ggplot2::geom_point(alpha = 0.75, size = 2.3) + ggplot2::geom_smooth(method = "lm", se = TRUE)
${facetLine}
p <- p + ggplot2::theme_classic(base_size = 13) + ggplot2::labs(title = ${rString(describeGraphType(graphType))}, x = x_axis, y = y_axis)
ggplot2::ggsave(file.path(output_dir, "requested_graph.png"), p, width = 7, height = 5, dpi = 300)
print(p)
`;
  }

  if (graphType === "paired_before_after") {
    const subject = design.subjectIdColumn ?? "YOUR_SUBJECT_ID_COLUMN";
    return `
# ---- 5. Requested graph: ${describeGraphType(graphType)} ----
x_axis <- ${rString(xAxis)}
y_axis <- ${rString(yAxis)}
subject_id <- ${rString(subject)}
p <- ggplot2::ggplot(analysis_data, ggplot2::aes(x = .data[[x_axis]], y = .data[[y_axis]], group = .data[[subject_id]])) +
  ggplot2::geom_line(alpha = 0.45) +
  ggplot2::geom_point(size = 2.3) +
  ggplot2::theme_classic(base_size = 13) +
  ggplot2::labs(title = ${rString(describeGraphType(graphType))}, x = x_axis, y = y_axis)
${facetLine}
ggplot2::ggsave(file.path(output_dir, "requested_graph.png"), p, width = 7, height = 5, dpi = 300)
print(p)
`;
  }

  if (graphType === "categorical_bar") {
    return `
# ---- 5. Requested graph: ${describeGraphType(graphType)} ----
x_axis <- ${rString(xAxis)}
y_axis <- ${rString(yAxis)}
p <- ggplot2::ggplot(analysis_data, ggplot2::aes(x = .data[[x_axis]], fill = .data[[y_axis]])) +
  ggplot2::geom_bar(position = "fill") +
  ggplot2::theme_classic(base_size = 13) +
  ggplot2::labs(title = ${rString(describeGraphType(graphType))}, x = x_axis, y = "Proportion", fill = y_axis)
${facetLine}
ggplot2::ggsave(file.path(output_dir, "requested_graph.png"), p, width = 7, height = 5, dpi = 300)
print(p)
`;
  }

  const geom = graphType === "violin_points"
    ? "ggplot2::geom_violin(trim = FALSE, alpha = 0.35)"
    : graphType === "bar_points"
      ? "ggplot2::stat_summary(fun = mean, geom = \"bar\", alpha = 0.55)"
      : "ggplot2::geom_boxplot(outlier.shape = NA, alpha = 0.45)";
  const points = graphSpec.showIndividualPoints
    ? "+ ggplot2::geom_jitter(width = 0.12, alpha = 0.65, size = 1.9)"
    : "";

  return `
# ---- 5. Requested graph: ${describeGraphType(graphType)} ----
x_axis <- ${rString(xAxis)}
y_axis <- ${rString(yAxis)}
color_by <- ${colorBy ? rString(colorBy) : "NULL"}
p <- ggplot2::ggplot(analysis_data, ggplot2::aes(x = .data[[x_axis]], y = .data[[y_axis]]))
if (!is.null(color_by)) p <- p + ggplot2::aes(fill = .data[[color_by]])
p <- p + ${geom} ${points}
${errorBar === "SEM" ? "p <- p + ggplot2::stat_summary(fun.data = ggplot2::mean_se, geom = \"errorbar\", width = 0.18)" : ""}
${facetLine}
p <- p + ggplot2::theme_classic(base_size = 13) + ggplot2::labs(title = ${rString(describeGraphType(graphType))}, x = x_axis, y = y_axis)
ggplot2::ggsave(file.path(output_dir, "requested_graph.png"), p, width = 7, height = 5, dpi = 300)
print(p)
`;
}

function textOutputBlock(input: RCodeInput): string {
  const { design, recommendation, selectedOutputs } = input;
  const methods = recommendation.suggestedFormula
    ? `Data were analyzed using ${recommendation.recommendedAnalysis} with formula ${recommendation.suggestedFormula}.`
    : `Data were analyzed using ${recommendation.recommendedAnalysis}.`;
  const results = [
    "Replace this template with the observed statistic, p-value, confidence interval, and direction of effect.",
    design.statisticalQuestion ? `Statistical question: ${design.statisticalQuestion}` : "",
    "Example: The model/test indicated [describe direction], statistic = [value], p = [value]."
  ].filter(Boolean).join(" ");

  const lines = ["# ---- 6. Draft report text ----"];
  if (outputSelected(selectedOutputs, "methods_sentence")) {
    lines.push(`methods_text <- ${rString(methods)}`);
    lines.push("writeLines(methods_text, file.path(output_dir, \"methods_text.txt\"))");
  }
  if (outputSelected(selectedOutputs, "results_sentence")) {
    lines.push(`results_template <- ${rString(results)}`);
    lines.push("writeLines(results_template, file.path(output_dir, \"results_template.txt\"))");
  }
  if (!outputSelected(selectedOutputs, "methods_sentence") && !outputSelected(selectedOutputs, "results_sentence")) {
    lines.push("# Methods/results text was not requested.");
  }
  return `${lines.join("\n")}\n`;
}

export function generateRAnalysisCode(input: RCodeInput): string {
  const requestedOutputLabels = input.selectedOutputs.length ? input.selectedOutputs.join(", ") : "not specified";
  const graphDescription = input.graphSpec?.graphRequested
    ? `${describeGraphType(input.graphSpec.graphType)} (${input.graphSpec.graphRequestText || "default graph plan"})`
    : "No graph requested.";

  return [
    "# Statistics Navigator R script",
    `# Recommended analysis: ${input.recommendation.recommendedAnalysis}`,
    `# Requested outputs: ${requestedOutputLabels}`,
    `# Graph request: ${graphDescription}`,
    "",
    setupBlock(input),
    coercionBlock(input),
    analysisBlock(input),
    graphBlock(input),
    textOutputBlock(input),
    "message(\"Done. Outputs were written to: \", normalizePath(output_dir))",
    ""
  ].join("\n");
}
